translation_explorer:
    resource: "@DarkTranslationBundle/Controller/ExplorerController.php"
    type:     annotation

translation_docs:
    resource: "@DarkTranslationBundle/Controller/DocsController.php"
    type:     annotation